# Generated by Django 3.2.8 on 2021-10-17 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('startTime', models.TimeField(blank=True, help_text='Starting time', verbose_name='Starting time')),
                ('endTime', models.TimeField(blank=True, help_text='Ending time', verbose_name='Ending time')),
                ('description', models.TextField(blank=True, help_text='Event description', null=True, verbose_name='Event description')),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
